# Generated by Django 4.2.19 on 2025-03-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="preferred_identifiers",
            field=models.ManyToManyField(blank=True, to="account.businessidentifier"),
        ),
    ]
