# Generated by Django 5.1.3 on 2025-02-25 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="is_staff",
            new_name="is_verified",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_active",
        ),
        migrations.AddField(
            model_name="customuser",
            name="verification_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
