# Generated by Django 5.1.7 on 2025-04-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_passwordresetcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetcode",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
