# Generated by Django 4.2.19 on 2025-03-31 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_businessidentifier_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessidentifier",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
