# Generated by Django 5.1.3 on 2025-03-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_businessprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[("customer", "Customer"), ("business", "Business")],
                default="customer",
                max_length=10,
            ),
        ),
    ]
