# Generated by Django 5.1.7 on 2025-04-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_passwordresetcode_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="passwordresetcode",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="passwordresetcode",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
