# Generated by Django 5.1.3 on 2025-03-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_customuser_is_staff_alter_customuser_is_superuser_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessprofile",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="businessprofile",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="businessprofile",
            name="street_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="businessprofile",
            name="zip_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
