# Generated by Django 5.1.3 on 2025-03-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_alter_businessprofile_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessprofile",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
