# Generated by Django 5.1.7 on 2025-04-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_customuser_deleted_customuser_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessprofile",
            name="category",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="businessprofile",
            name="flyerHeadline",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="businessprofile",
            name="flyerMessage",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
