# Generated by Django 5.1.3 on 2025-03-07 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_customerprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerprofile",
            name="previous_perks",
        ),
        migrations.CreateModel(
            name="Perk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("expiration_date", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("redeemed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_perks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perks",
                        to="account.businessprofile",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="current_perk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_perk",
                to="account.perk",
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="previous_perks",
            field=models.ManyToManyField(
                blank=True, related_name="previous_perks", to="account.perk"
            ),
        ),
    ]
