# Generated by Django 5.1.3 on 2025-03-07 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_remove_customerprofile_previous_perks_perk_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="perk",
            name="assigned_to",
        ),
        migrations.RemoveField(
            model_name="perk",
            name="expiration_date",
        ),
        migrations.RemoveField(
            model_name="perk",
            name="redeemed",
        ),
        migrations.AddField(
            model_name="perk",
            name="redemptions",
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name="perk",
            name="remaining",
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name="perk",
            name="title",
            field=models.CharField(default=True),
        ),
        migrations.AddField(
            model_name="perk",
            name="total",
            field=models.IntegerField(default=True),
        ),
    ]
