# Generated by Django 5.1.3 on 2025-03-08 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0010_alter_perk_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perk",
            name="redemptions",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="perk",
            name="remaining",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="perk",
            name="total",
            field=models.IntegerField(default=0),
        ),
    ]
