# Generated by Django 5.1.3 on 2025-03-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0011_alter_perk_redemptions_alter_perk_remaining_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="businessprofile",
            name="qr_code",
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="qr_code_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
