# Generated by Django 5.1.3 on 2025-03-13 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0013_businessprofile_onboarded"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_onboarded",
            field=models.BooleanField(default=False),
        ),
    ]
