# Generated by Django 5.1.3 on 2025-03-13 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0014_customuser_is_onboarded"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="businessprofile",
            name="onboarded",
        ),
    ]
