# Generated by Django 5.1.3 on 2025-03-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0015_remove_businessprofile_onboarded"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="website",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
