# Generated by Django 5.1.3 on 2025-03-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0016_businessprofile_phone_businessprofile_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessprofile",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="businessprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="businessprofile",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
