# Generated by Django 5.1.3 on 2025-03-15 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "account",
            "0017_businessprofile_category_alter_businessprofile_phone_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="perk",
            name="ended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
