# Generated by Django 5.1.3 on 2025-03-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0018_perk_ended_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessIdentifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="identifiers",
            field=models.ManyToManyField(blank=True, to="account.businessidentifier"),
        ),
    ]
