# Generated by Django 5.1.3 on 2025-03-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0019_businessidentifier_businessprofile_identifiers"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessprofile",
            name="logo",
            field=models.URLField(blank=True, null=True),
        ),
    ]
